import {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowBigDown,
  ArrowBigDownIcon,
  ArrowBigRight,
  ArrowBigRightIcon,
  ArrowBigUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CalculatorIcon,
  ChartColumnBigIcon,
  ChartPieIcon,
  CheckCircle2Icon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CoinsIcon,
  CreditCard,
  DeleteIcon,
  DivideIcon,
  EllipsisIcon,
  EqualIcon,
  EyeOffIcon,
  FileQuestion,
  HomeIcon,
  InfoIcon,
  LandmarkIcon,
  LanguagesIcon,
  MinusIcon,
  MoonIcon,
  PaletteIcon,
  PencilIcon,
  PiggyBankIcon,
  PlusCircleIcon,
  PlusIcon,
  SettingsIcon,
  Smartphone,
  SmartphoneNfc,
  StarIcon,
  SunIcon,
  Trash2Icon,
  TrashIcon,
  UserRoundIcon,
  WalletIcon,
  XIcon,
} from 'lucide-react-native';

import { iconWithClassName } from '@/lib/icon-with-classname';

iconWithClassName(HomeIcon);
iconWithClassName(ChartColumnBigIcon);
iconWithClassName(ChartPieIcon);
iconWithClassName(UserRoundIcon);
iconWithClassName(WalletIcon);
iconWithClassName(PlusIcon);
iconWithClassName(ArrowBigDown);
iconWithClassName(ArrowBigUpIcon);
iconWithClassName(ArrowBigRight);
iconWithClassName(AlertTriangleIcon);
iconWithClassName(AlertCircleIcon);
iconWithClassName(InfoIcon);
iconWithClassName(EllipsisIcon);
iconWithClassName(StarIcon);
iconWithClassName(CheckCircle2Icon);
iconWithClassName(CheckIcon);
iconWithClassName(PencilIcon);
iconWithClassName(DeleteIcon);
iconWithClassName(TrashIcon);
iconWithClassName(Trash2Icon);
iconWithClassName(XIcon);
iconWithClassName(ArrowLeftIcon);
iconWithClassName(EqualIcon);
iconWithClassName(ChevronLeftIcon);
iconWithClassName(CalculatorIcon);
iconWithClassName(DivideIcon);
iconWithClassName(MinusIcon);
iconWithClassName(ArrowRightIcon);
iconWithClassName(ArrowBigRightIcon);
iconWithClassName(ChevronRightIcon);
iconWithClassName(PlusCircleIcon);
iconWithClassName(ArrowBigDownIcon);
iconWithClassName(ChevronDownIcon);
iconWithClassName(CheckCircleIcon);
iconWithClassName(SettingsIcon);
iconWithClassName(PaletteIcon);
iconWithClassName(LanguagesIcon);
iconWithClassName(Smartphone);
iconWithClassName(MoonIcon);
iconWithClassName(SunIcon);
iconWithClassName(SmartphoneNfc);
iconWithClassName(CoinsIcon);
iconWithClassName(PiggyBankIcon);
iconWithClassName(CreditCard);
iconWithClassName(LandmarkIcon);
iconWithClassName(FileQuestion);
iconWithClassName(EyeOffIcon);

export {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowBigDown,
  ArrowBigDownIcon,
  ArrowBigRight,
  ArrowBigRightIcon,
  ArrowBigUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CalculatorIcon,
  ChartColumnBigIcon,
  ChartPieIcon,
  CheckCircle2Icon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CoinsIcon,
  CreditCard,
  DeleteIcon,
  DivideIcon,
  EllipsisIcon,
  EqualIcon,
  EyeOffIcon,
  FileQuestion,
  HomeIcon,
  InfoIcon,
  LandmarkIcon,
  LanguagesIcon,
  MinusIcon,
  MoonIcon,
  PaletteIcon,
  PencilIcon,
  PiggyBankIcon,
  PlusCircleIcon,
  PlusIcon,
  SettingsIcon,
  Smartphone,
  SmartphoneNfc,
  StarIcon,
  SunIcon,
  Trash2Icon,
  TrashIcon,
  UserRoundIcon,
  WalletIcon,
  XIcon,
};
