import {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowBigDown,
  ArrowBigRight,
  ArrowBigUpIcon,
  ArrowLeftIcon,
  CalculatorIcon,
  ChartColumnBigIcon,
  ChartPieIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronLeftIcon,
  DeleteIcon,
  DivideIcon,
  EllipsisIcon,
  EqualIcon,
  HomeIcon,
  InfoIcon,
  MinusIcon,
  PencilIcon,
  PlusIcon,
  StarIcon,
  Trash2Icon,
  TrashIcon,
  UserRoundIcon,
  WalletIcon,
  XIcon,
} from 'lucide-react-native';

import { iconWithClassName } from '@/lib/icon-with-classname';

iconWithClassName(HomeIcon);
iconWithClassName(ChartColumnBigIcon);
iconWithClassName(ChartPieIcon);
iconWithClassName(UserRoundIcon);
iconWithClassName(WalletIcon);
iconWithClassName(PlusIcon);
iconWithClassName(ArrowBigDown);
iconWithClassName(ArrowBigUpIcon);
iconWithClassName(ArrowBigRight);
iconWithClassName(AlertTriangleIcon);
iconWithClassName(AlertCircleIcon);
iconWithClassName(InfoIcon);
iconWithClassName(EllipsisIcon);
iconWithClassName(StarIcon);
iconWithClassName(CheckCircle2Icon);
iconWithClassName(CheckIcon);
iconWithClassName(PencilIcon);
iconWithClassName(DeleteIcon);
iconWithClassName(TrashIcon);
iconWithClassName(Trash2Icon);
iconWithClassName(XIcon);
iconWithClassName(ArrowLeftIcon);
iconWithClassName(EqualIcon);
iconWithClassName(ChevronLeftIcon);
iconWithClassName(CalculatorIcon);
iconWithClassName(DivideIcon);
iconWithClassName(MinusIcon);

export {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowBigDown,
  ArrowBigRight,
  ArrowBigUpIcon,
  ArrowLeftIcon,
  CalculatorIcon,
  ChartColumnBigIcon,
  ChartPieIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronLeftIcon,
  DeleteIcon,
  DivideIcon,
  EllipsisIcon,
  EqualIcon,
  HomeIcon,
  InfoIcon,
  MinusIcon,
  PencilIcon,
  PlusIcon,
  StarIcon,
  Trash2Icon,
  TrashIcon,
  UserRoundIcon,
  WalletIcon,
  XIcon,
};
